controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

client_new:
    path: /client/new
    controller: App\Controller\ClientController::new